language: elixir

os: linux

dist: xenial

elixir:
  - 1.8.1

otp_release:
  - 21.2

sudo: required

before_install:
  - set -e
  - mix local.hex --force
  - mix hex.organization auth community --key $HEXPM_KEY

script:
  - set -e
  - mix format --check-formatted --dry-run
  - mix lint.credo
  - mix test
