language: elixir

os: linux

dist: xenial

elixir:
  - 1.8.1

otp_release:
  - 21.2

sudo: required

cache:
  directories:
    - deps

before_install:
  - set -e
  - mix local.hex --force
  - sleep 1

script:
  - set -e
  - mix format --check-formatted
  - mix test
