version: 1

update_configs:
  - package_manager: "elixir:hex"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          dependency_name: "linter"
    default_labels:
      - "Ready for Review"
